import { ArrowDown, ArrowUpRight, Coffee, Croissant, Heart, MapPin, Utensils } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Button } from '../components/Button'
import { MenuCard } from '../components/MenuCard'
import { Reveal } from '../components/Reveal'
import { SectionHeading } from '../components/SectionHeading'
import { galleryImages } from '../data/gallery'
import { menuItems } from '../data/menu'

export function Home({ onReserve }: { onReserve: () => void }) {
  const featured = menuItems.filter(item => item.featured).slice(0, 6)
  return <main>
    <section className="hero"><div className="hero-image" /><div className="hero-shade" /><div className="container hero-content"><Reveal><span className="eyebrow eyebrow-light">Mumbai · Est. 2024</span><h1>Good coffee.<br /><em>Slow mornings.</em></h1><p className="hero-tagline">Better conversations.</p><p className="hero-description">A neighbourhood cafe for considered coffee, generous plates and the pleasure of taking your time.</p><div className="hero-actions"><Button variant="light" asLink href="/menu">Explore menu</Button><Button variant="outline" onClick={onReserve}>Reserve a table</Button></div></Reveal></div><div className="container hero-meta"><span><span className="open-dot" /> Open today · until 10pm</span><span className="hero-location"><MapPin size={14} /> 24 Blue Street, Mumbai</span><ArrowDown className="hero-scroll" size={20} /></div></section>
    <section className="section featured-section"><div className="container"><Reveal><div className="section-top"><SectionHeading eyebrow="From the kitchen" title={<>A little something <em>special</em></>} description="Our menu follows the day: bright in the morning, generous by noon, and quietly indulgent after dark." /><Link className="text-link" to="/menu">View full menu <ArrowUpRight size={16} /></Link></div></Reveal><div className="menu-grid">{featured.map((item, index) => <Reveal key={item.id} delay={index * .06}><MenuCard item={item} /></Reveal>)}</div></div></section>
    <section className="story-band"><div className="container story-grid"><Reveal className="story-image-wrap"><img src="https://images.unsplash.com/photo-1511081692775-05d0f180a065?auto=format&fit=crop&w=1200&q=85" alt="Friends sharing coffee across a cafe table" loading="lazy" /><span className="image-note">A table for every kind of day</span></Reveal><Reveal className="story-copy" delay={.1}><span className="eyebrow">The Cafe Blues way</span><h2>Come for the coffee.<br /><em>Stay for the feeling.</em></h2><p>We built Cafe Blues around a simple idea: that the best parts of a day rarely arrive in a hurry. Our coffee is precise, our food is generous, and the room is yours for as long as you need it.</p><Link className="text-link" to="/about">Read our story <ArrowUpRight size={16} /></Link></Reveal></div></section>
    <section className="section experience-section"><div className="container"><Reveal><SectionHeading eyebrow="Take your time" title={<>The good stuff is <em>in the details.</em></>} /></Reveal><div className="experience-grid"><Reveal delay={.05}><div className="experience-item"><span className="experience-number">01</span><Coffee /><h3>Specialty coffee</h3><p>Thoughtfully sourced beans, dialled in every morning, served without the fuss.</p></div></Reveal><Reveal delay={.12}><div className="experience-item"><span className="experience-number">02</span><Croissant /><h3>Fresh kitchen</h3><p>Seasonal plates and house bakes made for the pace of real life.</p></div></Reveal><Reveal delay={.19}><div className="experience-item"><span className="experience-number">03</span><Heart /><h3>Cozy atmosphere</h3><p>Sun-warmed corners, good records, and room for one more at the table.</p></div></Reveal></div></div></section>
    <section className="quote-section"><div className="container quote-inner"><span className="quote-mark">“</span><blockquote>Some places serve coffee.<br /><em>We create moments.</em></blockquote><span className="quote-line" /><span className="eyebrow">Cafe Blues, Mumbai</span></div></section>
    <section className="section gallery-section"><div className="container"><Reveal><div className="section-top"><SectionHeading eyebrow="A look around" title={<>The room between <em>moments.</em></>} /><p className="gallery-note">Come as you are.<br />Leave a little lighter.</p></div></Reveal><div className="gallery-grid">{galleryImages.map((image, index) => <Reveal key={image.src} delay={index * .04} className={`gallery-image gallery-${index + 1}`}><img src={image.src} alt={image.alt} loading="lazy" /></Reveal>)}</div></div></section>
    <section className="location-section" id="location"><div className="container location-grid"><Reveal><span className="eyebrow">Find your way here</span><h2>See you on<br /><em>Blue Street.</em></h2><address><MapPin size={17} /> 24 Blue Street, Fort<br />Mumbai, Maharashtra 400001</address><a className="text-link" href="https://maps.google.com/?q=24+Blue+Street+Mumbai" target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={16} /></a></Reveal><Reveal className="hours-panel" delay={.1}><div className="hours-icon"><Utensils size={18} /></div><span className="eyebrow">Opening hours</span><div className="hours-row"><span>Monday — Friday</span><b>8:00 AM — 10:00 PM</b></div><div className="hours-row"><span>Saturday — Sunday</span><b>9:00 AM — 11:00 PM</b></div><span className="hours-note"><span className="open-dot" /> Kitchen closes 30 min before</span></Reveal></div></section>
    <section className="final-cta"><div className="container final-cta-inner"><Reveal><span className="eyebrow eyebrow-light">Make a little room</span><h2>Your table<br /><em>is waiting.</em></h2><div className="hero-actions"><Button variant="light" onClick={onReserve}>Reserve a table</Button><Button variant="outline" asLink href="/menu">Explore menu</Button></div></Reveal></div></section>
  </main>
}
