import { Check, X } from 'lucide-react'
import { useState } from 'react'
import { Button } from './Button'

export function ReservationModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [submitted, setSubmitted] = useState(false)
  if (!open) return null
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true) }
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="reservation-modal" role="dialog" aria-modal="true" aria-labelledby="reservation-title"><button className="modal-close" onClick={onClose} aria-label="Close reservation form"><X size={20} /></button>{submitted ? <div className="success-state"><span className="success-icon"><Check /></span><span className="eyebrow">Request received</span><h2>We’ll hold the thought.</h2><p>Your table request is ready for our team to review. This is a demo, so no reservation has been placed.</p><Button onClick={onClose}>Close</Button></div> : <><span className="eyebrow">A place at the table</span><h2 id="reservation-title">Reserve a table</h2><p className="modal-intro">Tell us when you’d like to linger. We’ll confirm availability with you directly.</p><form className="reservation-form" onSubmit={submit}><label>Name<input required name="name" placeholder="Your name" /></label><div className="form-row"><label>Date<input required type="date" name="date" /></label><label>Time<select required name="time" defaultValue=""><option value="" disabled>Select time</option><option>9:00 AM</option><option>11:30 AM</option><option>1:00 PM</option><option>6:30 PM</option><option>8:30 PM</option></select></label></div><label>Guests<select required name="guests" defaultValue="2"><option value="1">1 guest</option><option value="2">2 guests</option><option value="3">3 guests</option><option value="4">4 guests</option><option value="5">5+ guests</option></select></label><label>Special request <span className="optional">Optional</span><textarea name="request" placeholder="A birthday, a favourite table..." rows={3} /></label><Button type="submit" className="form-submit">Request a table</Button></form></>}</div></div>
}
